# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [4]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()
array_1d = np.array([1, 2, 3, 4, 5])

# Create a 2-dimensional NumPy array using np.array()
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)

# Create a 1-dimensional NumPy array
array_1d = np.array([1, 2, 3, 4, 5])

# Get the shape of the array (number of elements along each axis)
shape = array_1d.shape

# Get the number of dimensions of the array
num_dimensions = array_1d.ndim

# Get the data type (dtype) of the array
data_type = array_1d.dtype

# Get the size (total number of elements) of the array
size = array_1d.size

# Get the type of the array (NumPy ndarray)
array_type = type(array_1d)

# Print the attributes
print("Shape:", shape)
print("Number of Dimensions:", num_dimensions)
print("Data Type:", data_type)
print("Size:", size)
print("Type:", array_type)



Shape: (5,)
Number of Dimensions: 1
Data Type: int64
Size: 5
Type: <class 'numpy.ndarray'>


In [7]:
# Attributes of 2-dimensional array

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Get the shape of the array (number of rows, number of columns)
shape = array_2d.shape

# Get the number of dimensions of the array
num_dimensions = array_2d.ndim

# Get the data type (dtype) of the array
data_type = array_2d.dtype

# Get the size (total number of elements) of the array
size = array_2d.size

# Get the type of the array (NumPy ndarray)
array_type = type(array_2d)

# Print the attributes
print("Shape:", shape)
print("Number of Dimensions:", num_dimensions)
print("Data Type:", data_type)
print("Size:", size)
print("Type:", array_type)


Shape: (3, 3)
Number of Dimensions: 2
Data Type: int64
Size: 9
Type: <class 'numpy.ndarray'>


In [8]:
# Attributes of 3-dimensional array

array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])

# Get the shape of the array (number of "slices," number of rows, number of columns)
shape = array_3d.shape

# Get the number of dimensions of the array
num_dimensions = array_3d.ndim

# Get the data type (dtype) of the array
data_type = array_3d.dtype

# Get the size (total number of elements) of the array
size = array_3d.size

# Get the type of the array (NumPy ndarray)
array_type = type(array_3d)

# Print the attributes
print("Shape:", shape)
print("Number of Dimensions:", num_dimensions)
print("Data Type:", data_type)
print("Size:", size)
print("Type:", array_type)


Shape: (3, 2, 3)
Number of Dimensions: 3
Data Type: int64
Size: 18
Type: <class 'numpy.ndarray'>


In [9]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

# Create a 2-dimensional NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a DataFrame from the NumPy array
df = pd.DataFrame(array_2d)

# Display the DataFrame
print(df)


   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [10]:
# Create an array of shape (10, 2) with only ones

ones_array = np.ones((10, 2))

# Display the array
print(ones_array)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
# Create a NumPy array of shape (7, 2, 3) with zeros
zeros_array = np.zeros((7, 2, 3))

# Display the array
print(zeros_array)


[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [12]:
# Create an array within a range of 0 and 100 with step 3

array_with_range = np.arange(0, 100, 3)

# Display the array
print(array_with_range)


[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [13]:
# Create a random array with numbers between 0 and 10 of size (7, 2)

random_array = 10 * np.random.rand(7, 2)

# Display the array
print(random_array)


[[2.25586849 8.54713115]
 [8.94484667 1.48975406]
 [6.09648961 2.69491562]
 [7.59745773 3.98735071]
 [5.366657   0.64919895]
 [8.22348602 1.09805316]
 [2.00065605 3.54515631]]


In [14]:
# Create a random array of floats between 0 & 1 of shape (3, 5)

random_array = np.random.rand(3, 5)

# Display the array
print(random_array)


[[0.22311188 0.96178472 0.782132   0.72884383 0.10498308]
 [0.02380192 0.7626205  0.82340238 0.79830714 0.70584647]
 [0.44589051 0.43761224 0.04040567 0.43284544 0.1483754 ]]


In [15]:
# Set the random seed to 42

np.random.seed(42)

# Create a random array of numbers between 0 and 10, with size (4, 6)
random_array = 10 * np.random.rand(4, 6)

# Display the array
print(random_array)


[[3.74540119 9.50714306 7.31993942 5.98658484 1.5601864  1.5599452 ]
 [0.58083612 8.66176146 6.01115012 7.08072578 0.20584494 9.69909852]
 [8.32442641 2.12339111 1.81824967 1.8340451  3.04242243 5.24756432]
 [4.31945019 2.9122914  6.11852895 1.39493861 2.92144649 3.66361843]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [16]:
# Create a random array of numbers between 1 and 10, with size (3, 7)
random_array = np.random.randint(1, 11, size=(3, 7))

# Display the array
print("Random Array:")
print(random_array)

# Find the unique numbers in the array
unique_numbers = np.unique(random_array)

# Display the unique numbers
print("\nUnique Numbers:")
print(unique_numbers)



Random Array:
[[ 3  7  4  9  3  5  3]
 [ 7  5  9  7  2  4  9]
 [ 2 10  9 10  5  2  4]]

Unique Numbers:
[ 2  3  4  5  7  9 10]


In [17]:

# Find the value at the 0'th index
value_at_index_0 = unique_numbers[0]

# Display the value
print("Value at 0'th index:", value_at_index_0)



Value at 0'th index: 2


In [18]:
# Get the first 2 rows
first_2_rows = unique_numbers[:2]

# Display the first 2 rows
print("First 2 Rows:")
print(first_2_rows)


First 2 Rows:
[2 3]


In [20]:
# Get the first 2 values of the first 2 rows
first_2_values = unique_numbers[:2]

# Display the first 2 values of the first 2 rows
print("First 2 Values of the First 2 Rows:")
print(first_2_values)


First 2 Values of the First 2 Rows:
[2 3]


In [21]:
# Create a random array of numbers between 0 and 10, size (3, 5)
random_array = 10 * np.random.rand(3, 5)

# Create an array of ones, size (3, 5)
ones_array = np.ones((3, 5))

# Display the arrays
print("Random Array:")
print(random_array)
print("\nOnes Array:")
print(ones_array)



Random Array:
[[2.41025466 6.83263519 6.09996658 8.33194912 1.73364654]
 [3.91060608 1.82236088 7.5536141  4.25155874 2.07941663]
 [5.67700328 0.31313292 8.42284775 4.49754133 3.95150236]]

Ones Array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
# Create a random array of numbers between 0 and 10, size (3, 5)
random_array = 10 * np.random.rand(3, 5)

# Create an array of ones, size (3, 5)
ones_array = np.ones((3, 5))

# Add the two arrays together
result_array = random_array + ones_array

# Display the result
print("Result Array (Random Array + Ones Array):")
print(result_array)


Result Array (Random Array + Ones Array):
[[10.26658866  8.27271996  4.26540769  6.70443974  6.2083426 ]
 [10.61172024  9.44533849  8.4732011   6.39692132  6.86751166]
 [10.65255307  7.07034248  3.75999182  3.96273506  2.65266939]]


In [23]:
# Create an array of ones with shape (5, 3)
ones_array_2 = np.ones((5, 3))

# Display the new array
print("Ones Array 2:")
print(ones_array_2)


Ones Array 2:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
# Create another array of ones with shape (5, 3)
ones_array_2 = np.ones((5, 3))

# Display the new array
print("Ones Array 2:")
print(ones_array_2)

# Transpose ones_array_2 to make it (3, 5)
ones_array_2_transposed = ones_array_2.T

# Add the transposed ones_array_2 and result_array
result = result_array + ones_array_2_transposed

# Display the result
print("\nResult (Adding Transposed Ones Array 2 and Result Array):")
print(result)



Ones Array 2:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Result (Adding Transposed Ones Array 2 and Result Array):
[[11.26658866  9.27271996  5.26540769  7.70443974  7.2083426 ]
 [11.61172024 10.44533849  9.4732011   7.39692132  7.86751166]
 [11.65255307  8.07034248  4.75999182  4.96273506  3.65266939]]


When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [25]:
# Create another array of ones with shape (3, 5)
ones_array_3 = np.ones((3, 5))

# Display the new array
print("Ones Array 3:")
print(ones_array_3)



Ones Array 3:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
# Create another array of ones with shape (3, 5)
ones_array_3 = np.ones((3, 5))

# Display the new array
print("Ones Array 3")



Ones Array 3


In [29]:
# Multiply the array of ones (shape 3, 5) by the most recent array (shape 3, 5)
result_after_multiplication = ones_array_3 * result

# Display the result
print("Result After Multiplication:")
print(result_after_multiplication)


Result After Multiplication:
[[11.26658866  9.27271996  5.26540769  7.70443974  7.2083426 ]
 [11.61172024 10.44533849  9.4732011   7.39692132  7.86751166]
 [11.65255307  8.07034248  4.75999182  4.96273506  3.65266939]]


In [30]:
# Raise the latest array to the power of 2
result_power_of_2 = result_after_multiplication ** 2

# Display the result
print("Result After Raising to the Power of 2:")
print(result_power_of_2)



Result After Raising to the Power of 2:
[[126.93601999  85.98333543  27.72451812  59.35839177  51.96020304]
 [134.83204701 109.1050961   89.74153911  54.71444507  61.89773967]
 [135.78199311  65.13042769  22.65752213  24.62873925  13.34199368]]


In [31]:
# Do the same thing with np.square()
# Use np.square() to square the latest array
result_square = np.square(result_after_multiplication)

# Display the result
print("Result After Squaring Using np.square():")
print(result_square)


Result After Squaring Using np.square():
[[126.93601999  85.98333543  27.72451812  59.35839177  51.96020304]
 [134.83204701 109.1050961   89.74153911  54.71444507  61.89773967]
 [135.78199311  65.13042769  22.65752213  24.62873925  13.34199368]]


In [32]:
# Find the mean of the latest array using np.mean()

mean_result = np.mean(result_square)

# Display the mean
print("Mean of the Latest Array:")
print(mean_result)



Mean of the Latest Array:
70.91960074471837


In [33]:
# Find the maximum of the latest array using np.max()

max_result = np.max(result_square)

# Display the maximum
print("Maximum of the Latest Array:")
print(max_result)



Maximum of the Latest Array:
135.78199311072407


In [34]:

# Find the minimum of the latest array using np.min()
min_result = np.min(result_square)

# Display the minimum
print("Minimum of the Latest Array:")
print(min_result)



Minimum of the Latest Array:
13.341993677245515


In [35]:
# Find the standard deviation of the latest array using np.std()
std_deviation_result = np.std(result_square)

# Display the standard deviation
print("Standard Deviation of the Latest Array:")
print(std_deviation_result)

Standard Deviation of the Latest Array:
39.993989093287674


In [36]:
# Find the variance of the latest array using np.var()
variance_result = np.var(result_square)

# Display the variance
print("Variance of the Latest Array:")
print(variance_result)

Variance of the Latest Array:
1599.5191635940132


In [37]:
# Reshape the latest array to (3, 5, 1)
reshaped_result = result_square.reshape(3, 5, 1)

# Display the reshaped array
print("Reshaped Array to (3, 5, 1):")
print(reshaped_result)


Reshaped Array to (3, 5, 1):
[[[126.93601999]
  [ 85.98333543]
  [ 27.72451812]
  [ 59.35839177]
  [ 51.96020304]]

 [[134.83204701]
  [109.1050961 ]
  [ 89.74153911]
  [ 54.71444507]
  [ 61.89773967]]

 [[135.78199311]
  [ 65.13042769]
  [ 22.65752213]
  [ 24.62873925]
  [ 13.34199368]]]


In [38]:
# Transpose the latest array
# Transpose the latest array using np.transpose()
transposed_result = np.transpose(reshaped_result)

# Display the transposed array
print("Transposed Array:")
print(transposed_result)


Transposed Array:
[[[126.93601999 134.83204701 135.78199311]
  [ 85.98333543 109.1050961   65.13042769]
  [ 27.72451812  89.74153911  22.65752213]
  [ 59.35839177  54.71444507  24.62873925]
  [ 51.96020304  61.89773967  13.34199368]]]


What does the transpose do?

In [40]:
# Create an array of random integers between 0 and 10, size (3, 3)
array1 = np.random.randint(0, 11, size=(3, 3))

# Create another array of random integers between 0 and 10, size (3, 2)
array2 = np.random.randint(0, 11, size=(3, 2))

# Display both arrays
print("Array 1 (3x3):")
print(array1)

print("\nArray 2 (3x2):")
print(array2)

Array 1 (3x3):
[[ 8  6  8]
 [ 7  0  7]
 [ 7 10  2]]

Array 2 (3x2):
[[ 0  7]
 [ 2  2]
 [ 0 10]]


In [ ]:
# Perform a dot product on the two newest arrays you created


In [41]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
# Create the first array of random integers between 0 and 10, size (4, 3)
array1 = np.random.randint(0, 11, size=(4, 3))

# Create the second array of random integers between 0 and 10, size (4, 3)
array2 = np.random.randint(0, 11, size=(4, 3))

# Display both arrays
print("Array 1 (4x3):")
print(array1)

print("\nArray 2 (4x3):")
print(array2)

Array 1 (4x3):
[[4 9 6]
 [9 8 6]
 [8 7 1]
 [0 6 6]]

Array 2 (4x3):
[[ 7  4  2]
 [ 7  5 10]
 [ 2  0  2]
 [ 4  2  0]]


In [42]:
# Perform a dot product on the two newest arrays you created
# Create the first array of random integers between 0 and 10, size (4, 3)
array1 = np.random.randint(0, 11, size=(4, 3))

# Create the second array of random integers between 0 and 10, size (4, 3)
array2 = np.random.randint(0, 11, size=(4, 3))

# Perform the dot product
dot_product_result = np.dot(array1, array2.T)

# Display the result
print("Dot Product Result:")
print(dot_product_result)

Dot Product Result:
[[ 84 132 126  83]
 [106 160 152 112]
 [ 75 150 148  72]
 [ 36  45  42  57]]


It doesn't work. How would you fix it?

In [43]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
# Create the first array of random integers between 0 and 10, size (4, 3)
array1 = np.random.randint(0, 11, size=(4, 3))

# Create the second array of random integers between 0 and 10, size (4, 3)
array2 = np.random.randint(0, 11, size=(4, 3))

# Transpose one of the arrays
array2_transposed = array2.T

# Perform the dot product
dot_product_result = np.dot(array1, array2_transposed)

# Display the result
print("Dot Product Result:")
print(dot_product_result)

Dot Product Result:
[[127 102 118  80]
 [137  98 175  64]
 [142 100 146  80]
 [ 24  48  80   0]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [44]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
# Create the first array of random integers between 0 and 10, size (4, 3)
array1 = np.random.randint(0, 11, size=(4, 3))

# Create the second array of random integers between 0 and 10, size (4, 3)
array2 = np.random.randint(0, 11, size=(4, 3))

# Display both arrays
print("Array 1 (4x3):")
print(array1)

print("\nArray 2 (4x3):")
print(array2)

Array 1 (4x3):
[[ 2  9  7]
 [10  5  7]
 [ 8  3  0]
 [ 0  9  3]]

Array 2 (4x3):
[[ 6  1  2]
 [ 0  4  0]
 [ 7  0 10]
 [ 0  1  1]]


In [45]:
# Compare the two arrays with '>'
# Create the two arrays of random integers between 0 and 10, both size (4, 3)
array1 = np.random.randint(0, 11, size=(4, 3))
array2 = np.random.randint(0, 11, size=(4, 3))

# Compare the two arrays element-wise with '>'
comparison_result = array1 > array2

# Display the comparison result
print("Comparison Result (array1 > array2):")
print(comparison_result)

Comparison Result (array1 > array2):
[[False False False]
 [False False False]
 [False False  True]
 [ True  True False]]


What happens when you compare the arrays with `>`?

In [46]:
# Compare the two arrays with '>='
# Create the two arrays of random integers between 0 and 10, both size (4, 3)
array1 = np.random.randint(0, 11, size=(4, 3))
array2 = np.random.randint(0, 11, size=(4, 3))

# Compare the two arrays element-wise with '>='
comparison_result = array1 >= array2

# Display the comparison result
print("Comparison Result (array1 >= array2):")
print(comparison_result)

Comparison Result (array1 >= array2):
[[ True False  True]
 [ True False  True]
 [False  True  True]
 [False  True False]]


In [47]:
# Find which elements of the first array are greater than 7
# Create the first array of random integers between 0 and 10, size (4, 3)
array1 = np.random.randint(0, 11, size=(4, 3))

# Find elements greater than 7 in the first array
condition = array1 > 7

# Get the elements that satisfy the condition
elements_greater_than_7 = array1[condition]

# Display the elements greater than 7
print("Elements in array1 greater than 7:")
print(elements_greater_than_7)

Elements in array1 greater than 7:
[8 8 9 9 8]


In [48]:
# Which parts of each array are equal? (try using '==')
# Create the two arrays of random integers between 0 and 10, both size (4, 3)
array1 = np.random.randint(0, 11, size=(4, 3))
array2 = np.random.randint(0, 11, size=(4, 3))

# Compare the two arrays element-wise with '=='
equality_result = array1 == array2

# Display the equality result
print("Equality Result (array1 == array2):")
print(equality_result)

Equality Result (array1 == array2):
[[False False False]
 [False False False]
 [False False False]
 [False False False]]


In [49]:
# Sort one of the arrays you just created in ascending order
# Create an array of random integers between 0 and 10, size (4, 3)
array_to_sort = np.random.randint(0, 11, size=(4, 3))

# Sort the array in ascending order
sorted_array = np.sort(array_to_sort)

# Display the sorted array
print("Sorted Array (Ascending Order):")
print(sorted_array)

Sorted Array (Ascending Order):
[[2 2 8]
 [1 1 8]
 [1 2 5]
 [0 3 8]]


In [50]:
# Sort the indexes of one of the arrays you just created
# Create an array of random integers between 0 and 10, size (4, 3)
array_to_sort = np.random.randint(0, 11, size=(4, 3))

# Get the sorted indexes
sorted_indexes = np.argsort(array_to_sort, axis=None)

# Display the sorted indexes
print("Sorted Indexes:")
print(sorted_indexes)

Sorted Indexes:
[ 1  8  9  7 11  0  3  2  6  4  5 10]


In [51]:
# Find the index with the maximum value in one of the arrays you've created
# Create an array of random integers between 0 and 10, size (4, 3)
array_to_find_max_index = np.random.randint(0, 11, size=(4, 3))

# Find the index with the maximum value
max_index = np.argmax(array_to_find_max_index)

# Convert the flattened index to row and column indices
row_index, col_index = np.unravel_index(max_index, array_to_find_max_index.shape)

# Display the maximum value and its index
print("Maximum Value:", array_to_find_max_index[row_index, col_index])
print("Index with Maximum Value (Row, Column):", (row_index, col_index))

Maximum Value: 10
Index with Maximum Value (Row, Column): (2, 2)


In [52]:
# Find the index with the minimum value in one of the arrays you've created
# Create an array of random integers between 0 and 10, size (4, 3)
array_to_find_min_index = np.random.randint(0, 11, size=(4, 3))

# Find the index with the minimum value
min_index = np.argmin(array_to_find_min_index)

# Convert the flattened index to row and column indices
row_index, col_index = np.unravel_index(min_index, array_to_find_min_index.shape)

# Display the minimum value and its index
print("Minimum Value:", array_to_find_min_index[row_index, col_index])
print("Index with Minimum Value (Row, Column):", (row_index, col_index))

Minimum Value: 0
Index with Minimum Value (Row, Column): (0, 0)


In [53]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
# Create an array of random integers between 0 and 10, size (4, 3)
array_to_find_max_indexes = np.random.randint(0, 11, size=(4, 3))

# Find the indexes with the maximum values along axis 1
max_indexes_axis_1 = np.argmax(array_to_find_max_indexes, axis=1)

# Display the indexes with the maximum values along axis 1
print("Indexes with Maximum Values along Axis 1:")
print(max_indexes_axis_1)

Indexes with Maximum Values along Axis 1:
[1 0 2 1]


In [54]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
# Create an array of random integers between 0 and 10, size (4, 3)
array_to_find_min_indexes = np.random.randint(0, 11, size=(4, 3))

# Find the indexes with the minimum values along axis 0
min_indexes_axis_0 = np.argmin(array_to_find_min_indexes, axis=0)

# Display the indexes with the minimum values along axis 0
print("Indexes with Minimum Values along Axis 0:")
print(min_indexes_axis_0)

Indexes with Minimum Values along Axis 0:
[3 2 0]


In [55]:
# Create an array of normally distributed random numbers
# Create an array of normally distributed random numbers
mean = 0  # Mean of the distribution
std_dev = 1  # Standard deviation of the distribution
size = (4, 3)  # Size of the array

# Generate the array of random numbers
normal_distribution_array = np.random.normal(mean, std_dev, size)

# Display the array
print("Array of Normally Distributed Random Numbers:")
print(normal_distribution_array)

Array of Normally Distributed Random Numbers:
[[-1.02549987 -1.18303961  0.44977404]
 [ 1.77892434 -0.66694337 -1.69181826]
 [ 0.65679733 -1.43590082 -1.18326562]
 [ 0.49499565 -0.16530961 -0.68717518]]


In [56]:
# Create an array with 10 evenly spaced numbers between 1 and 100

evenly_spaced_array = np.linspace(1, 100, 10)

# Display the array
print("Array with 10 Evenly Spaced Numbers between 1 and 100:")
print(evenly_spaced_array)


Array with 10 Evenly Spaced Numbers between 1 and 100:
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.